spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coffeemachine
    username: machine
    password: pass
  data.rest:
    basePath: /coffeemachine
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  charset:
    console: "UTF-8"
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n"
  level:
    org.springframework: INFO
