spring:
  profiles:
    active: dev
  config:
    import: consumables.yaml
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /coffeemachine
  error:
    whitelabel:
      enabled: false

---
# Developer profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coffeemachine
    tcp: jdbc:h2:tcp://localhost:9092/mem:coffeemachine
    username: machine
    password: pass
  sql:
    init:
      #data-locations: classpath:schema-h2.sql
      mode: always
      platform: h2
  h2:
    console.enabled: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coffeemachine
    username: machine
    password: pass
  sql:
    init:
      #data-locations: classpath:schema-postgresql.sql
      mode: always
      platform: postgresql